export type IntegrationStage = "SOURCE_OBSERVED" | "SOURCE_FINALIZED" | "SOURCE_VERIFIED" | "DESTINATION_SIMULATED" | "DESTINATION_SUBMITTED" | "DESTINATION_FINALIZED" | "RECONCILED" | "COMPLETED" | "BLOCKED";
const ALLOWED: Record<IntegrationStage, readonly IntegrationStage[]> = {
  SOURCE_OBSERVED:["SOURCE_FINALIZED","BLOCKED"], SOURCE_FINALIZED:["SOURCE_VERIFIED","BLOCKED"], SOURCE_VERIFIED:["DESTINATION_SIMULATED","BLOCKED"], DESTINATION_SIMULATED:["DESTINATION_SUBMITTED","BLOCKED"], DESTINATION_SUBMITTED:["DESTINATION_FINALIZED","BLOCKED"], DESTINATION_FINALIZED:["RECONCILED","BLOCKED"], RECONCILED:["COMPLETED","BLOCKED"], COMPLETED:[], BLOCKED:[]
};
export function assertIntegrationTransition(from: IntegrationStage, to: IntegrationStage): void { if (!ALLOWED[from].includes(to)) throw new Error(`PWRC_INTEGRATION_INVALID_TRANSITION:${from}->${to}`); }
