export type BridgeTransferState =
  | "CREATED"
  | "SOURCE_SUBMITTED"
  | "SOURCE_FINALIZED"
  | "SOURCE_VERIFIED"
  | "DESTINATION_BUILT"
  | "DESTINATION_SIMULATED"
  | "DESTINATION_SUBMITTED"
  | "DESTINATION_FINALIZED"
  | "RECONCILED"
  | "COMPLETED"
  | "BLOCKED";

const transitions: Record<
  BridgeTransferState,
  readonly BridgeTransferState[]
> = {
  CREATED: ["SOURCE_SUBMITTED", "BLOCKED"],
  SOURCE_SUBMITTED: ["SOURCE_FINALIZED", "BLOCKED"],
  SOURCE_FINALIZED: ["SOURCE_VERIFIED", "BLOCKED"],
  SOURCE_VERIFIED: ["DESTINATION_BUILT", "BLOCKED"],
  DESTINATION_BUILT: ["DESTINATION_SIMULATED", "BLOCKED"],
  DESTINATION_SIMULATED: ["DESTINATION_SUBMITTED", "BLOCKED"],
  DESTINATION_SUBMITTED: ["DESTINATION_FINALIZED", "BLOCKED"],
  DESTINATION_FINALIZED: ["RECONCILED", "BLOCKED"],
  RECONCILED: ["COMPLETED", "BLOCKED"],
  COMPLETED: [],
  BLOCKED: ["SOURCE_VERIFIED", "DESTINATION_BUILT", "RECONCILED"],
};

export function assertBridgeTransferTransition(
  from: BridgeTransferState,
  to: BridgeTransferState,
): void {
  if (!transitions[from].includes(to)) {
    throw new Error(`PWRC_BRIDGE_INVALID_TRANSITION:${from}->${to}`);
  }
}
