[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pwrc_lock = "7JAV3PsxkHh5oKAFDMKqVpKaV2P2P5Vj3Qv15hH8wPwr"
pwrc_token = "PWRCpWCpQ8BRn3pzMnvaTzMK9Q2GsxuLx7QgJgduLSu"

[programs.devnet]
pwrc_token = "PWRCpWCpQ8BRn3pzMnvaTzMK9Q2GsxuLx7QgJgduLSu"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
