[package]
name = "pwrc-lock"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "pwrc_lock"


[features]
default = []
idl-build = [
  "anchor-lang/idl-build",
]

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
