[package]
name = "pwrc-lock"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "PowerChain canonical PWRC Solana lock/release bridge program"

[lib]
crate-type = ["cdylib", "lib"]
name = "pwrc_lock"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build",
]

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
